# -*- coding: utf-8 -*-
"""myntra_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qIVX04y8iXIqdFvEvROo_qyn00qb5IVI
"""

import pandas as pd
df=pd.read_csv('/content/Myntra_Fasion_Clothing[1].csv')
df.info()

df.head(15)

df.shape
df.columns
df.describe()

df.isnull().sum()

df=df.drop(['URL','Description','SizeOption'],axis=1)

df.head()

df['DiscountPrice (in Rs)']=df['DiscountPrice (in Rs)'].fillna(df['OriginalPrice (in Rs)'])

df['Ratings']=df['Ratings'].fillna(df['Ratings'].median())

df['Reviews']=df['Reviews'].fillna(0)

df['DiscountOffer']=df['DiscountOffer'].fillna(0)

df.isnull().sum()

df.duplicated().sum()

"""**Feature Engineering**"""

df['DiscountPercent']=(df['OriginalPrice (in Rs)']-df['DiscountPrice (in Rs)'])/(df['OriginalPrice (in Rs)']*100)

df['PriceCategory']=pd.cut(df['OriginalPrice (in Rs)'],bins=[0,500,1500,3000,10000],labels=['Budget','Mid','Premium','Luxury'])

import seaborn as sns
sns.boxplot(x=df['OriginalPrice (in Rs)'])

df[['OriginalPrice (in Rs)','DiscountPrice (in Rs)','Ratings','Reviews']].corr()

sns.histplot(df['OriginalPrice (in Rs)'],bins=50)

sns.histplot(df['Ratings'],bins=50)

sns.scatterplot(x=df['OriginalPrice (in Rs)'],y=df['Ratings'])

sns.scatterplot(x=df['DiscountPercent'],y=df['Reviews'])

sns.countplot(x=df['category_by_Gender'])

df.to_csv("myntra_clean_dataset.csv",index=False)

from google.colab import files
files.download("myntra_clean_dataset.csv")